#!/bin/bash

cp /lab/data/emt2/2012/1206/120619/*atoms25244.fit /home/yihan/monitor/example
sleep 10
cp /lab/data/emt2/2012/1206/120619/*atoms25245.fit /home/yihan/monitor/example
sleep 10
cp /lab/data/emt2/2012/1206/120619/*atoms25246.fit /home/yihan/monitor/example
