#!/bin/bash


if [[ $1 == -h || $# -eq 0 ]]
then 
	echo ""
	echo "  out2INI:"
        echo ""
	echo "  Given an out file, this script translates the out file with"
	echo "  5 digits shot number to a corresponding 4 digits report file"
	echo "  that stores the information in a [SECTION] key = value manner"
	echo ""
	echo "  usage: out2INI [#####.out]"
	echo ""
	echo "  Example:"
	echo ""
	echo "  ./out2INI 54321.out  ==> report4321.INI"   
	exit 2
fi


shot=`/home/yihan/monitor/translate/4digits $1`
shotfivedig=`echo $1 | sed 's/\.out//'`
echo "wini $shot SEQ:shot $shotfivedig"
wini $shot SEQ:shot $shot
fitfun=`/home/yihan/monitor/translate/grepData $1 | awk 'NR ==1 {print}'`
echo "wini $shot OUT:fitfun $fitfun"
wini $shot OUT:fitfun $fitfun
imaging=`/home/yihan/monitor/translate/grepData $1 | awk 'NR == 6 {print}'`
echo "wini $shot OUT:imaging $imaging"
wini $shot OUT:imaging "$imaging"

nfields=`/home/yihan/monitor/translate/grepData $1 | awk 'NR == 2 { print NF}'`

for (( i = 2; i<=$nfields; i++))
do
	key=`/home/yihan/monitor/translate/grepData $1 | awk -v field=$i 'NR == 2 { print $field}'`
	value=`/home/yihan/monitor/translate/grepData $1 | awk -v field=$i 'NR == 3 { print $field}'`
	echo "wini $shot OUT:$key $value"
	wini `/home/yihan/monitor/translate/4digits $1`  OUT:$key $value
done

nfields_err=`/home/yihan/monitor/translate/grepData $1 | awk 'NR == 5 {print NF}'` 

for (( i = 2; i<=$nfields_err; i++))
do
	key_err=`/home/yihan/monitor/translate/grepData $1 | awk -v field=$i 'NR == 4 {print $field}'`
	value_err=`/home/yihan/monitor/translate/grepData $1 | awk -v field=$i 'NR == 5 {print $field}'`
	echo "wini $shot OUT:$key_err $value_err"
	wini $shot OUT:$key_err $value_err
done

#echo "nfields = $nfields"
#echo "nfields_err = $nfields_err"

x0=`/home/yihan/monitor/translate/grepCrop $1 | awk '{print$1}'`
x1=`/home/yihan/monitor/translate/grepCrop $1 | awk '{print$2}'`
y0=`/home/yihan/monitor/translate/grepCrop $1 | awk '{print$3}'`
y1=`/home/yihan/monitor/translate/grepCrop $1 | awk '{print$4}'`
echo "wini $shot CROPWIN:x0 $x0"
wini $shot CROPWIN:x0 $x0
echo "wini $shot CROPWIN:x1 $x1"
wini $shot CROPWIN:x1 $x1
echo "wini $shot CROPWIN:y0 $y0"
wini $shot CROPWIN:y0 $y0
echo "wini $shot CROPWIN:y1 $y1"
wini $shot CROPWIN:y1 $y1

norm=`/home/yihan/monitor/translate/grepNorm $1 | awk 'NR == 1 {print$1}'`
normvar=`/home/yihan/monitor/translate/grepNorm $1 | awk 'NR == 2 {print$1}'` 
echo "wini $shot NORM:$norm $normvar"
wini $shot NORM:$norm $normvar

flags=`/home/yihan/monitor/translate/grepFlags $1`
echo "wini $shot FLAGS:flagsstr $flags"
wini $shot FLAGS:flagsstr "$flags"
